defmodule NBC.Repo.Migrations.ChangeFieldBikesPlaceUidToPlaceNumber do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:bikes), :place_uid, to: :place_number
    execute string_to_int()
  end

  def down do
    execute int_to_string()
    rename table(:bikes), :place_number, to: :place_uid
  end

  defp string_to_int() do
    "alter table bikes alter place_number type bigint using place_number::bigint"
  end

  defp int_to_string() do
    "alter table bikes alter place_number type text using place_number::text"
  end
end
